x = input('Digite algo: ')
print(f'{x} é do tipo primitivo: ',type(x))
print(x,'Possui somente espaço?',x.isspace())
print(x, 'Possui apenas letras?',x.isalpha(), '!')
print(x, 'Possui apenas números?', x.isnumeric(), '!')
print(x, 'Possui letra ou número?', x.isalnum(), '!')
print(x, 'Possui apenas letras maiúsculas?', x.isupper(), '!')
print(x, 'Possui apenas letras minúsculas?', x.islower(), '!')
print(x, 'Está capitalizada?', x.istitle(), '!')