nome = str(input('Digite seu nome completo: ')).strip()
nomed = nome.split()
nomej = '-'.join(nomed)
esp = nomej.count('-')
print('Analisando seu nome...')
print(f'Seu nome em letras maiúsculas é: {nome.upper()}')
print(f'Seu nome em minúsculas é: {nome.lower()}')
print(f'Seu nome tem ao todo {(len(nome) - nome.count(" "))} letras')
print(f'Seu primeiro nome é {nomed[0]} e ele tem {len(nomed[0])} letra.')